version: '3.8'

services:
    fontend:
      build: ./example-frontend
      ports:
        - 5000:5000

    backend:
      build: ./example-backend
      ports:
        - 8080:8080
      environment:
        - REDIS_HOST=redis
      
    redis:
      image: redis
      ports:
        - 6379:6379
