version: '3.8'

services:
    db:
      image: postgres
      restart: unless-stopped
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - database:/var/lib/postgresql/data
      container_name: dev-postgres
    
volumes:
  database: