version: '3.8'

services:
    db:
      image: postgres
      restart: unless-stopped
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=test_user
        - POSTGRES_HOST=localhost
        - POSTGRES_PASSWORD=test_pass
        - POSTGRES_DB=test_db
      volumes:
        - database:/var/lib/postgresql/data
      container_name: postgres
    
volumes:
  database: