version: '3.8'

services:
    fontend:
      build: ./example-frontend
      ports:
        - 5000:5000

    backend:
      build: ./example-backend
      ports:
        - 8080:8080
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DATABASE=postgres
      
    redis:
      image: redis
      ports:
        - 6379:6379

    postgres:
      image: postgres
      restart: unless-stopped
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=postgres
      volumes:
        - ./database:/var/lib/postgresql/data
volumes:
  database: