version: '3.8'

services:
    frontend:
      build: ./example-frontend
      ports:
        - 5000:5000
      container_name: frontend

    backend:
      build: ./example-backend
      ports:
        - 8080:8080
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DATABASE=postgres
      container_name: backend
      
    redis:
      image: redis
      ports:
        - 6379:6379

    postgres:
      image: postgres
      restart: unless-stopped
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=postgres
      volumes:
        - ./database:/var/lib/postgresql/data
    
    proxy:
      image: nginx
      ports:
        - 80:80
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
volumes:
  database: